# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "NMiNxrwH8BWd2aiQwozyN9run2b/4JxWOdCR5ELs2ZoBsxOPMr7zQh3J+Omi6HjpZ9toHv7V0fP15hzvZ7FE03EkHkvq1WIYTr4wXlK1aW28SeLKAAXmf73IeAATt5QX1d3VSdcSb106gDYN9S6F48RmnOTyvso8NZFeQ59Z1vD5iNeHvazGMAlUTQdfyq0onzQIX4wOYD8hJW2ADA44J+M5YQ9Qk1nvpnbASWSx8DTFBfUTEnCeyU+07WCDyzmpiYKY3IzbOEkCUmo9Tmbq0tF7vIhEfcMEirG/G41R8WM/cj6dI4VzA1J6DkDBCuWNHZExQsP5jKkmYXXAuD78ojTG36aXzTiSniX64VUBzakFk0BDnHQ9FMRgmzre7QydrTUkO4/zjtHFQaOKSPGFQNstUCOfMwv1P06izZdB2fFF4BClDNU8G2S//gd2SS4dRDyWxB9+EpXdhs7Q9VRfTSwjdhU8Qmo29PFZU2Nj6KYVutY3vcbaFHAky0xWXfOd3aqja4ZZrHJXouL9TEdiJJ8UP5zBNDW2tBw731BwSx//Slxhu6mJY8Qvjl3RscMiubURDoSuDtUE6bx2fEMGDQz5K37UPAR/5UL8vYOhXwd3iokeTsuyNS5Wjp8nAE+VYkFSiGjUQ5MoAQfPy2cUd5YnkUKqfSypCMFiJYh0U7Y="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
