github:
  user_or_org: CoralieXXC
travis:
  secure:
    BINSTAR_TOKEN: NMiNxrwH8BWd2aiQwozyN9run2b/4JxWOdCR5ELs2ZoBsxOPMr7zQh3J+Omi6HjpZ9toHv7V0fP15hzvZ7FE03EkHkvq1WIYTr4wXlK1aW28SeLKAAXmf73IeAATt5QX1d3VSdcSb106gDYN9S6F48RmnOTyvso8NZFeQ59Z1vD5iNeHvazGMAlUTQdfyq0onzQIX4wOYD8hJW2ADA44J+M5YQ9Qk1nvpnbASWSx8DTFBfUTEnCeyU+07WCDyzmpiYKY3IzbOEkCUmo9Tmbq0tF7vIhEfcMEirG/G41R8WM/cj6dI4VzA1J6DkDBCuWNHZExQsP5jKkmYXXAuD78ojTG36aXzTiSniX64VUBzakFk0BDnHQ9FMRgmzre7QydrTUkO4/zjtHFQaOKSPGFQNstUCOfMwv1P06izZdB2fFF4BClDNU8G2S//gd2SS4dRDyWxB9+EpXdhs7Q9VRfTSwjdhU8Qmo29PFZU2Nj6KYVutY3vcbaFHAky0xWXfOd3aqja4ZZrHJXouL9TEdiJJ8UP5zBNDW2tBw731BwSx//Slxhu6mJY8Qvjl3RscMiubURDoSuDtUE6bx2fEMGDQz5K37UPAR/5UL8vYOhXwd3iokeTsuyNS5Wjp8nAE+VYkFSiGjUQ5MoAQfPy2cUd5YnkUKqfSypCMFiJYh0U7Y=
appveyor:
  secure:
    BINSTAR_TOKEN: v1EyMFXVuIuz4bN6Z9nzCjqn5hpjur/mjjl/EwHQWZnt/v1r7rS+I/cznyAKHFVC
